/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

/**
 *
 * @author DIYAS
 */
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Dataproduk extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    DefaultTableModel modell;
    public Dataproduk() {
        initComponents();
        String [] judul = {"Kode Produk","Nama Produk", "Gambar Produk", "Kategori", "Supplier", "Harga Jual","Harga Beli","Stok Produk"};
        modell =new DefaultTableModel (judul, 0);
        jTable1.setModel(modell);
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        closee = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btntambah = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 255));
        jLabel1.setText("DATA PRODUK");

        closee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-close-30.png"))); // NOI18N
        closee.setBorder(null);
        closee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closee)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(closee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Produk", "Nama Produk", "Gambar Produk", "Kategori", "Supplier", "Harga Jual", "Harga Beli", "Stok Produk"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btntambah.setBackground(new java.awt.Color(51, 255, 51));
        btntambah.setForeground(new java.awt.Color(0, 0, 0));
        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(51, 255, 255));
        btnupdate.setForeground(new java.awt.Color(0, 0, 0));
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(255, 51, 51));
        btnhapus.setForeground(new java.awt.Color(0, 0, 0));
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnrefresh.setBackground(new java.awt.Color(0, 0, 0));
        btnrefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(139, 139, 139)
                            .addComponent(btntambah)
                            .addGap(79, 79, 79)
                            .addComponent(btnupdate)
                            .addGap(85, 85, 85)
                            .addComponent(btnhapus)
                            .addGap(70, 70, 70)
                            .addComponent(btnrefresh))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntambah)
                    .addComponent(btnupdate)
                    .addComponent(btnhapus)
                    .addComponent(btnrefresh))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        
        TambahDP tdp = new TambahDP(this, true);
        tdp.setLocationRelativeTo(this); 
        tdp.setVisible(true);

    }//GEN-LAST:event_btntambahActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        // Mendapatkan baris yang dipilih di JTable
    int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow >= 0) {
        // Mengambil data produk yang dipilih
        String kodeProduk = jTable1.getValueAt(selectedRow, 0).toString();  // Kode Produk ada di kolom pertama
        String namaProduk = jTable1.getValueAt(selectedRow, 1).toString();  // Nama Produk di kolom kedua
        String gambarProduk = jTable1.getValueAt(selectedRow, 2).toString();  // Gambar Produk di kolom ketiga
        String kategoriProduk = jTable1.getValueAt(selectedRow, 3).toString();  // Kategori di kolom keempat
        String supplier = jTable1.getValueAt(selectedRow, 4).toString();  // Supplier di kolom kelima
        double hargaJual = Double.parseDouble(jTable1.getValueAt(selectedRow, 5).toString());  // Harga Jual di kolom keenam
        double hargaBeli = Double.parseDouble(jTable1.getValueAt(selectedRow, 6).toString());  // Harga Beli di kolom ketujuh
        int stokProduk = Integer.parseInt(jTable1.getValueAt(selectedRow, 7).toString());  // Stok Produk di kolom kedelapan

        // Membuka form update dengan data yang sudah dipilih
        TambahDP tdp = new TambahDP(this, true);
        tdp.setLocationRelativeTo(this); 
 
        tdp.setKodeProduk(kodeProduk);  // Set Kode Produk
        tdp.setNamaProduk(namaProduk);  // Set Nama Produk
        tdp.setGambarProduk(gambarProduk);  // Set Gambar Produk
        tdp.setKategoriProduk(kategoriProduk);  // Set Kategori Produk
        tdp.setSupplier(supplier);  // Set Supplier
        tdp.setHargaJual(hargaJual);  // Set Harga Jual
        tdp.setHargaBeli(hargaBeli);  // Set Harga Beli
        tdp.setStokProduk(stokProduk);  // Set Stok Produk
        tdp.setVisible(true);  // Menampilkan form update
    } else {
        JOptionPane.showMessageDialog(this, "Silakan pilih produk yang ingin diupdate.");
    }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void closeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeeActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeeActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        
        if (selectedRow >=0){
            String kodeProduk = jTable1.getValueAt(selectedRow, 0).toString();
            
            int confirm = JOptionPane.showConfirmDialog(null,  "Apakah Anda yakin ingin menghapus produk dengan kode: " + kodeProduk + "?", 
                    "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION){
                //Proses menghapus dari database
                try{
                    Connection con = dbkoneksi.konfig.sambung();
                    String sql = "DELETE FROM data_produk WHERE kode_produk = ?";
                    PreparedStatement pst = con.prepareStatement(sql);
                    pst.setString(1, kodeProduk); //mengikat kode produk ke query
                    
                    //menjalankan query
                    int result = pst.executeUpdate();
                    
                    if (result > 0){
                        JOptionPane.showMessageDialog(null, "Produk berhasil dihapus");
                        tampil();
                    }else{
                        JOptionPane.showMessageDialog(null, "Produk gagal dihapus");
                    }
                } catch (SQLException ex){
                    Logger.getLogger(Dataproduk.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menghapus produk" + ex.getMessage());
                }
            }
        }else {
            JOptionPane.showMessageDialog(this, "Silahkan pilih produk yang ingin dihapus");
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        // TODO add your handling code here:
        tampil();
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("kode_produk");
        tbl.addColumn("nama_produk");
        tbl.addColumn("gambar_produk");
        tbl.addColumn("kategori_produk");
        tbl.addColumn("supplier");
        tbl.addColumn("harga_jual");
        tbl.addColumn("harga_beli");
        tbl.addColumn("stok_produk");
        
        try {
            Connection con = dbkoneksi.konfig.sambung();
            String cari = jTextField1.getText();
            ResultSet rs = con.createStatement().executeQuery("SELECT * FROM data_produk WHERE nama_produk like '%"+cari+"%'");
            while (rs.next()){
                tbl.addRow(new Object[]{
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),
                    rs.getString(8),
                    rs.getString(9)
                });
            }
            
            jTable1.setModel(tbl);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"ada kesalahan"+ e);
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dataproduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dataproduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dataproduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dataproduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dataproduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton closee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    public void tampil() {
//        int row = jTable1.getRowCount();
//        for(int a= 0; a<row;a++){
//            modell.setRowCount(0);
//        }
        try {
            Connection con = dbkoneksi.konfig.sambung();
            String sql = "SELECT * FROM data_produk";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            modell.setRowCount(0);
//            ResultSet rs = con.createStatement().executeQuery("SELECT * FROM data_produk");
            while (rs.next()) {
                Object[] row = {
                    rs.getString("kode_produk"),
                    rs.getString("nama_produk"),
                    rs.getString("gambar_produk"),
                    rs.getString("kategori_produk"),
                    rs.getString("supplier"),
                    rs.getDouble("harga_jual"),
                    rs.getDouble("harga_beli"),
                    rs.getInt("stok_produk")
                };
//                String data []= {rs.getString(2),rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6),
//                    rs.getString(7), rs.getString(8), rs.getString(9)};
                modell.addRow(row);
            }
            jTable1.setModel(modell);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        }
    }
}
